ARG ODOO_VERSION
FROM odoo:${ODOO_VERSION}

ARG HOST
ENV HOST=${HOST}

ARG PORT=5432
ENV PORT=${PORT}


ARG POSTGRES_USER
ENV USER=${POSTGRES_USER}
ENV POSTGRES_USER=${POSTGRES_USER}

ARG POSTGRES_PASSWORD
ENV PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

ARG DATABASE_NAME
ENV DATABASE_NAME=${DATABASE_NAME}

RUN pip install watchdog


